# General configuration for Aider AI code assistant

# List of files or directories to include/exclude
include:
  - "**/*.js"
  - "**/*.ts"
  - "**/*.go"
  - "**/*.py"
  - "**/*.md"
  - "**/*.json"
  - "**/*.yml"
  - "**/*.yaml"
exclude:
  - "node_modules/"
  - "dist/"
  - "build/"
  - ".git/"
  - ".env"
  - "*.log"
  - ".DS_Store"

# Language and formatting preferences
language: "en"
code_style: "auto" # or "prettier", "gofmt", etc. depending on your stack

# AI model settings
model: "gemini/gemini-2.5-pro-preview-03-25" # or your preferred model

# Prompt and context settings
max_context_files: 10
max_context_tokens: 8000

# Commit message style
commit_message_template: |
  {summary}

  {details}

# Optional: Custom instructions for the AI
instructions: |
  - Write clear, idiomatic, and well-documented code.
  - Prefer readability over micro-optimizations.
  - Use best practices for security and maintainability.
  - When in doubt, ask for clarification.

# Optional: Environment variables to mask
mask_env:
  - "API_KEY"
  - "SECRET"
  - "PASSWORD"

# Optional: Pre- and post-command hooks
pre_commands: []
post_commands: []

# Optional: Custom file templates (for new files)
file_templates: {}
# End of config
